This notebook contains Helen's python code for loading and getting counts of the DC Inbox newletter content files.

In [2]:
# import libraries
import pandas as pd

In [3]:
# Read in the raw DCInbox table

dcinbox_raw_df = pd.read_csv(
    "../data/dcinbox/dcinbox_export_114.csv",
    # sep = ",",            # columns are separated by commas
    # encoding = "latin1",
    quotechar = '"',   # Make sure actual quotation marks in newsletters are handled right
    engine = 'python'    # This might be able to handle very long messages better
)

# Remove all unnamed columns, because they're messing up the read of the file
unnamed = dcinbox_raw_df.columns.str.contains('^Unnamed')
dcinbox_clean_columns_df = dcinbox_raw_df.loc[:, ~unnamed].copy()

dcinbox_clean_columns_df.head()

,Subject,Body,Unix Timestamp,BioGuide ID,Congress,First Name,Last Name,Date of Birth,Gender,State,District,Party,Chamber,Nickname,ID
0,Happy New Year!,Click here to open this e-mail in its own brow...,1.48339E+12,W000806,114,Daniel,Webster,4/27/49,M,FL,10,Republican,House,NaN,136125
1,Happy New Year!,Several Issa-Backed Bills Become Law View this...,1.48338E+12,I000056,114,Darrell,Issa,11/1/53,M,CA,49,Republican,House,NaN,136126
2,OH-12 Update / A Look Back at the 114th Congress,OH-12 Update / A Look Back at the 114th Congr...,1.48338E+12,T000462,114,Patrick,Tiberi,10/21/62,M,OH,12,Republican,House,Pat,136127
3,The Leader's Daily Schedule - 1/3/17,The Leader's Daily Schedule - 1/3/17 Kevin Mc...,1.48337E+12,M001165,114,Kevin,McCarthy,1/26/65,M,CA,23,Republican,House,NaN,136128
4,What I've Been Working On,Click here to open this e-mail in its own bro...,1.48337E+12,C001084,114,David,Cicilline,7/15/61,M,RI,1,Democrat,House,NaN,136129

In [4]:
# QC to make sure it's pulling in the right columns from DC Inbox data
print(dcinbox_clean_columns_df.columns)

Index(['Subject', 'Body', 'Unix Timestamp', 'BioGuide ID', 'Congress',
       'First Name', 'Last Name', 'Date of Birth', 'Gender', 'State',
       'District', 'Party', 'Chamber', 'Nickname', 'ID'],
      dtype='object')

In [5]:
# Field cleanup for DC Inbox table

# dcinbox_df = dcinbox_clean_columns_df
dcinbox_df = dcinbox_clean_columns_df.copy()

# Convert unix timestamp to a datetime column
dcinbox_df["Date"] = pd.to_datetime(
    pd.to_numeric(dcinbox_df["Unix Timestamp"], errors="coerce"),
    unit="ms"
).dt.date

# Convert district to an integer and fill senators with 0
dcinbox_df["District"] = (
    pd.to_numeric(dcinbox_df["District"], errors = "coerce")
    .fillna(0)
    .astype(int)
)

# create a column that is the uppercased, concatenated first and last name of the politician
# (for matching later to FEC data)
dcinbox_df["Full Name"] = dcinbox_df["First Name"].str.upper() + " " + dcinbox_df["Last Name"].str.upper()

# Rename party to party full
dcinbox_df.rename(columns={"Party": "Party Full"}, inplace=True)
# Add A new party column that just is one character mapped to D, R, or O (Other)
dcinbox_df["Party"] = (
    dcinbox_df["Party Full"]
    .fillna("")
    .astype(str)
    .str[0]
    .str.upper()
    .map({"D": "D", "R": "R"})
    .fillna("O")
)

# Make sure state and party are uppercased
dcinbox_df["State"] = dcinbox_df["State"].fillna("").str.strip().str.upper()
dcinbox_df["Party"] = dcinbox_df["Party"].str.upper()

# dcinbox_df.info()
dcinbox_df.head()

,Subject,Body,Unix Timestamp,BioGuide ID,Congress,First Name,Last Name,Date of Birth,Gender,State,District,Party Full,Chamber,Nickname,ID,Date,Full Name,Party
0,Happy New Year!,Click here to open this e-mail in its own brow...,1.48339E+12,W000806,114,Daniel,Webster,4/27/49,M,FL,10,Republican,House,NaN,136125,2017-01-02,DANIEL WEBSTER,R
1,Happy New Year!,Several Issa-Backed Bills Become Law View this...,1.48338E+12,I000056,114,Darrell,Issa,11/1/53,M,CA,49,Republican,House,NaN,136126,2017-01-02,DARRELL ISSA,R
2,OH-12 Update / A Look Back at the 114th Congress,OH-12 Update / A Look Back at the 114th Congr...,1.48338E+12,T000462,114,Patrick,Tiberi,10/21/62,M,OH,12,Republican,House,Pat,136127,2017-01-02,PATRICK TIBERI,R
3,The Leader's Daily Schedule - 1/3/17,The Leader's Daily Schedule - 1/3/17 Kevin Mc...,1.48337E+12,M001165,114,Kevin,McCarthy,1/26/65,M,CA,23,Republican,House,NaN,136128,2017-01-02,KEVIN MCCARTHY,R
4,What I've Been Working On,Click here to open this e-mail in its own bro...,1.48337E+12,C001084,114,David,Cicilline,7/15/61,M,RI,1,Democrat,House,NaN,136129,2017-01-02,DAVID CICILLINE,D

In [6]:
# Various checks on the fields in the raw data set

print(dcinbox_df["District"].unique())

dcinbox_df["Date"] = pd.to_datetime(dcinbox_df["Date"], errors='coerce')
print("Min Date:", dcinbox_df["Date"].min())
print("Max Date:", dcinbox_df["Date"].max())

print(dcinbox_df["Party Full"].unique())
print(dcinbox_df["Party"].unique())

[ 10  49  12  23   1   6   7   2   9   0  16   8  36  14   4  28   3  11
  27  13  18  33  26  50   5  24  34  32  25  21  30  29  17  22  51  38
  15  20  39  47  19  45  31  52  35  53 114  46  41  37 100  42  40  44]
Min Date: 1970-01-01 00:00:00
Max Date: 2017-01-02 00:00:00
['Republican' 'Democrat' nan
 ' the company agreed to provide an automatic one-month credit to all customers for each piece of overbilled equipment or service'
 ' a Republican'
 ' DC 20510 Phone: 202-224-3542 Fax: 202-224-7327 Toll Free for Nevadans: 1-866-SEN-REID (736-7343) Restricted to calls originating from area codes 775 and 702   - Privacy Policy - "'
 ' I hope someday I can change that. And as fortune would have it'
 ' and Rehabilitation Research For more information' ' Moore said'
 ' 2017 Expected Number of Awards: 4 Estimated Total Program Funding: $200'
 'John'
 ' approved the amendment with strong bipartisan support by a vote of 47-to-12. The Senate and House failed to come to an agreement on that long-term funding bill for the FAA'
 ' and refine their MVP. Team Sentinel now possesses a wireframe MVP - a basic idea of what the product would look like - that has buy-in from many of its stakeholders. The course is over'
 '624'
 ' it would be great to switch on Magic Carpet during a perfect-weather day and see how the pilots like it. ""I\'m expecting the fleet to incorporate Magic Carpet as a circus pass'
 ' 2016 Expected Number of Awards: 1 Estimated Total Program Funding: $250'
 ' will reduce utilization of our airframes'
 ' preparing to deploy later this year. The last time four strike groups were deployed simultaneously was over a nine-week period from late August 2012 to early November 2012'
 ' go to: Department of Health and Human Services Administration for Children and Families Grants to Address Trafficking within the Child Welfare Population Current Closing Date for Applications: July 11'
 ' the U.S. military is inadequately prepared for operations against enemies that field large numbers of capable PGMs. DoD has the opportunity to redress this situation by adopting new operational concepts and rebalancing its mix of air and missile defense capabilities. This will require congressional support for some new programs and an allocation of resources commensurate with this growing threat. The alternative of adhering to traditional concepts and capabilities for air and missile defense could invite potential adversaries to continue or accelerate their guided weapons investments'
 ' offered by Rep. Mike Coffman (R-Colo.)'
 '000 CFDA Number(s): 93.866 - Aging Research For more information'
 ' 2016 Estimated Total Program Funding: $2' ' Spain'
 ' Wildlife and Plant Conservation Resource Management For more information'
 '000 Expected Number of Awards: 10 NSFHP-16-FASTLANE16 FastLane Grants Department of Transportation CFDA Number(s): 20.934 -- Nationally Significant Freight and Highway Projects Posted Date: Mar 15'
 ' sailors pitch in with cooking - which Brasseur said has allowed the crew to share family recipes and traditional meals from their hometowns and home countries. The sailors also share in chores like washing dishes'
 " we're about to hit mid-life on LCS. The first two LCS out of production are about to do their mid-life in the next couple of years"
 '500' ' and we hope and expect you to work with us'
 " and we really had to scramble the last six weeks or so to cut $17 billion ... and it was only probably in the last ten days of our process that we knew what Congress had done to the '16 budget in the Omnibus Appropriations Bill"
 '000 CFDA Number(s): 95.008 - Drug-Free Communities Support Program - National Youth Leadership Initiative For more information'
 ' a Republican from Lake County'
 ' and Kidney Diseases Extramural Research For more information'
 ' 2015 Estimated Total Program Funding: $350'
 ' following its transition from the Lockheed Martin P-3C Orion MPA to the P-8A platform in early 2014. The Pelicans'
 ' lay pipelines. He stated that the location in Logan is particularly good because not only is it bringing jobs to the area'
 ' frankly' 'FL' ' the steepness of the share lines' ' said'
 ' it is not affecting us today'
 ' Forbes called the Navy\'s original plan to place the 11 cruisers in modernization at the same time ""a fantasy'
 '400'
 ' 2016 (Passed 255-163) H.R.2028 - Energy and Water Development and Related Agencies Appropriations Act'
 ' and Oman'
 ' go to: [link 89] Department of Justice Office of Justice Programs Office of Juvenile Justice Delinquency Prevention OJJDP FY 2015 VOCA Training and Technical Assistance for Child Abuse Prosecutors Current Closing Date for Applications: May 29'
 ' according to the 2014 report by the office of the director of operational test and evaluation. The office in October conducted an assessment of the alternate concepts developed by the small surface combatant task force. ""That assessment found that only major modifications to the existing LCS design'
 ' truncated training cycles' '4']
['R' 'D' 'O']

In [7]:
# QC of third party politicians (2015-2016 cycle)

independents = ["Sanders", "Gonzalez", "Amash", "King", "Sablan"]
indie_rows = dcinbox_df[dcinbox_df["Last Name"].isin(independents)]
print(indie_rows[["First Name", "Last Name", "Party", "District", "State"]].drop_duplicates())

      First Name Last Name Party  District State
40      Gregorio    Sablan     D         0    MP
1978      Justin     Amash     R         3    MI
2331       Angus      King     D         0    ME
4974       Steve      King     R         4    IA
17176    Bernard   Sanders     D         0    VT

In [8]:
# Make new data frame that only includes the distinct politicians with their Congress, 
# First Name, Last Name, Gender, State, District, and Party 
# to use for match targets

# Filter rows for desired cycle (here, the 114th Congress)
# and only House members
dcinbox_df["Date"] = pd.to_datetime(dcinbox_df["Date"])
date_filter = dcinbox_df["Date"].between("2015-01-03", "2017-01-02")
chamber_filter = dcinbox_df["Chamber"] == "House"
office_filter = dcinbox_df["District"] != 0

# pols_for_matching_df = dcinbox_df.loc[mask, ["Full Name", "Party", "State", "District"]]
# test_df = dcinbox_df.loc[date_filter & office_filter, ["Full Name", "Party", "State", "District"]]
# print(test_df["District"].value_counts())

# Create a data frame that only has the files we need for matching
# pols_matching_df = dcinbox_df[["Full Name", "Party", "State", "District"]].rename(
pols_matching_df = dcinbox_df.loc[date_filter & office_filter & chamber_filter, ["Full Name", "Party", "State", "District"]].rename(
    columns={
        "Full Name": "name",
        "Party": "match_attribute1",
        "State": "match_attribute2",
        "District": "match_attribute3"
    }
)

# Drop duplicate rows based on all columns
pols_matching_df = pols_matching_df.drop_duplicates()

# Adding blank columns needed for python matching process
pols_matching_df["id"] = ""
pols_matching_df["append_attribute1"] = ""
pols_matching_df["append_attribute2"] = ""
pols_matching_df["append_attribute3"] = ""

# Reordering columns so "id" is second
cols = ["name", "id", "match_attribute1", "match_attribute2", "match_attribute3",
        "append_attribute1", "append_attribute2", "append_attribute3"]
pols_matching_df = pols_matching_df[cols]

print(len(pols_matching_df))
print(pols_matching_df.head())

402
              name id match_attribute1 match_attribute2  match_attribute3  \
0   DANIEL WEBSTER                   R               FL                10
1     DARRELL ISSA                   R               CA                49
2   PATRICK TIBERI                   R               OH                12
3   KEVIN MCCARTHY                   R               CA                23
4  DAVID CICILLINE                   D               RI                 1

  append_attribute1 append_attribute2 append_attribute3
0
1
2
3
4

In [9]:
# Output the match targets to a CSV file (no longer %_test)

pols_matching_df.to_csv(
    "../matching/match_targets_2016.csv",
    index=False  # no row numbers
    # encoding="latin1"
)

In [10]:
# Column counts

# cand_contrib_df["CID"].nunique()
key_column_counts = dcinbox_df[["Full Name", "Party", "State", "District", "Gender"]].nunique()
print(key_column_counts)
# print(dcinbox_df["Chamber"].count())

Full Name    548
Party          3
State        102
District      54
Gender        48
dtype: int64